services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    container_name: car_prices_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
